name: accesos_directos
description: Aplicación de accesos directos con navegación interna

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.7
  # webview_cookie_manager: ^2.0.6  # Comentado por problemas de compatibilidad
  url_launcher: ^6.2.5
  sqflite: ^2.3.2
  path: ^1.8.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true